version: '3.0'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile-py
    container_name: gc01
    command: bash -c "./wait-for-it.sh db:5432 -- python manage.py db upgrade && gunicorn app:app --bind 0.0.0.0:8000"
    depends_on:
      - db
    expose:
      - "8000"
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: ps01
